
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Feb 09 00:03:15 CST 2019
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 7;
  public static final int UMENOS = 6;
  public static final int RESTA = 4;
  public static final int MULTIPLICACION = 3;
  public static final int error = 1;
  public static final int SUMA = 2;
  public static final int DIVISION = 5;
  public static final int EOF = 0;
}

