
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 05 23:40:51 CST 2019
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 4;
  public static final int MULTIPLICACION = 3;
  public static final int error = 1;
  public static final int SUMA = 2;
  public static final int EOF = 0;
}

